#!/usr/bin/python
import subprocess
import re

proc = subprocess.Popen(["git tag -l"], stdout=subprocess.PIPE, shell=True)
(out, err) = proc.communicate()

tags = out.splitlines()
print(tags)

def tag_value(tag):
    tag = re.sub('[^\\d\\.]', '', tag)
    parts = tag.split('.')
    places = [int(float(x)) for x in parts]
    value = 0
    place_value = 1
    for place in places:
        value = value + place * place_value
        place_value *= 0.01
    return value
    
tags.sort(key=tag_value)
print(tags[-1])
