#!/usr/bin/python
import subprocess
import re
import sys
DEBUG = False
if len(sys.argv) > 1:
    if sys.argv[1] == '-d':
        DEBUG = True

proc = subprocess.Popen(["git tag -l"], stdout=subprocess.PIPE, shell=True)
(out, err) = proc.communicate()

tags = out.splitlines()

def tag_value(tag):
    tag = re.sub('[^\\d\\.]', '', tag)
    parts = tag.split('.')
    parts = [x for x in parts if len(x.strip()) > 0]
    places = [int(float(x)) for x in parts]
    value = 0
    place_value = 1
    for place in places:
        value = value + place * place_value
        place_value *= 0.01
    return value
    
tags.sort(key=tag_value)
if DEBUG:
    print(tags)
print('#tags : {}'.format(len(tags)))
print('#highest : {}'.format(tags[-1]))
